export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

export const LOAD_REFERENTS_SUCCESS = "LOAD_REFERENTS_SUCCESS";
export const LOAD_REFERENTS_ERROR = "LOAD_REFERENTS_ERROR";
export const ADD_REFERENT_SUCCESS = "ADD_REFERENT_SUCCESS";
export const UPDATE_REFERENT_SUCCESS = "UPDATE_REFERENT_SUCCESS";

export const LOAD_ORGANIZATIONS_SUCCESS = "LOAD_ORGANIZATIONS_SUCCESS";
export const LOAD_ORGANIZATIONS_ERROR = "LOAD_ORGANIZATIONS_ERROR";
export const ADD_ORGANIZATION_SUCCESS = "ADD_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";

export const LOAD_PROGRAMS_SUCCESS = "LOAD_PROGRAMS_SUCCESS";
export const LOAD_PROGRAMS_ERROR = "LOAD_PROGRAMS_ERROR";
export const ADD_PROGRAM_SUCCESS = "ADD_PROGRAM_SUCCESS";
export const UPDATE_PROGRAM_SUCCESS = "UPDATE_PROGRAM_SUCCESS";

export const LOAD_CONFIG_SUCCESS = "LOAD_CONFIG_SUCCESS";
export const LOAD_LOV_SUCCESS = "LOAD_LOV_SUCCESS";

export const LOAD_ZONES_SUCCESS = "LOAD_ZONES_SUCCESS";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
